apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../bootstrap
  - ../../argocd/cluster-profiles/base
  - ../../argocd/app/openshift-gitops
  - ../../argocd/app/selfsigned-cluster-issuer
