apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/redhat-cop/gitops-catalog/openshift-dev-spaces/aggregate/overlays/default?ref=main
  - https://github.com/redhat-cop/gitops-catalog/web-terminal/operator/overlays/fast?ref=main
  - https://github.com/redhat-cop/gitops-catalog/web-terminal/instance/overlays/enhanced?ref=main
  - https://github.com/redhat-cop/gitops-catalog/redhat-developer-hub-operator/operator/overlays/fast?ref=main
  - https://github.com/redhat-cop/gitops-catalog/redhat-developer-hub-operator/instance/overlays/default?ref=main
  - https://github.com/redhat-cop/gitops-catalog/openshift-pipelines-operator/overlays/stable?ref=main
