apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - ../../operator-manifests/cert-manager-operator
  - ClusterIssuer_selfsigned-cluster-issuer.yaml

