apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../_manifest-template

patches:
  - target:
      kind: AppProject
      name: PLACEHOLDER
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: selfsigned-cluster-issuer
      spec:
        description: 'selfsigned-cluster-issuer Project'
        destinations:
          - name: in-cluster
            server: https://kubernetes.default.svc
            namespace: cert-manager
        clusterResourceWhitelist:
          - group: cert-manager.io
            kind: ClusterIssuer

    options:
      allowNameChange: true

transformers:
  - ../_manifest-template/transformers
