apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  disableNameSuffixHash: true

resources:
  - keycloak-tls-cert.yaml
  - keycloak.yaml
