apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  disableNameSuffixHash: true

secretGenerator:
  - files:
      - tls.crt=demo-tls/certificate.pem
      - tls.key=demo-tls/key.pem
    name: demo-tls-secret
    type: kubernetes.io/tls

resources:
  - keycloak.yaml
