apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    version: "8.10.4" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/<OPERATOR_VERSION>/CHART_VERSIONS
    values:
      global:
        hosts:
          domain: apps-crc.testing
        ingress:
          configureCertmanager: true
      certmanager-issuer:
        email: rhighley@redhat.com
