apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: AppProject
      name: PLACEHOLDER
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: cert-manager
      spec:
        description: 'cert-manager Project'
        destinations:
          - name: in-cluster
            namespace: '*'
    options:
      allowNameChange: true

transformers:
  - ../../base/transformers
