apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: AppProject
      name: PLACEHOLDER
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: cert-manager
      spec:
        description: 'cert-manager Project'
        destinations:
          - name: in-cluster
            server: https://kubernetes.default.svc
            namespace: '*'
        clusterResourceWhitelist:
          - group: cert-manager.io
            kind: ClusterIssuer
          - group: '*'
            kind: Namespace

    options:
      allowNameChange: true

transformers:
  - ../base/transformers
