---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-password
  namespace: gitea-repo
  labels:
    app: gitea-repo
type: Opaque
data:
  password: cjNkaDR0MSE=
---
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea-repo
  namespace: gitea-repo
  labels:
    app: gitea-repo
spec:
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaAdminPasswordExpose: false
  giteaAdminPasswordSecretName: gitea-admin-password
  giteaAdminUser: admin
  giteaDisableSsh: false
  giteaPostgresqlDatabaseName: giteadb
  giteaPostgresqlPassword: Qgs4C0MDdlkK2fup
  giteaPostgresqlServiceName: gitea-pgsql.gitea-repo.svc
  giteaPostgresqlUser: userIAE
  giteaSsl: true
  giteaStartSshServer: true
  giteaVolumeSize: 4Gi
  postgresqlSetup: false
---
