apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhbk-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  project: cluster-profile-operators
  source:
    repoURL: https://github.com/ryan-highley/stp-devops-config.git
    path: manifests/operator/rhbk-operator
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
