---
apiVersion: v1
kind: Namespace
metadata:
  name: red-hat-keycloak
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: red-hat-keycloak
spec:
  targetNamespaces:
    - red-hat-keycloak
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhbk-operator.stp-devops-keycloak: ''
  name: rhbk-operator
spec:
  channel: stable-v26.0
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
