apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-tls
spec:
  secretName: demo-tls-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h
  renewBefore: 360h
  isCA: false
  usages:
    - server auth
  commonName: keycloak.apps-crc.testing
  dnsNames:
    - stp-devops-keycloak-ingress-red-hat-keycloak.apps-crc.testing
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
