apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stp-devops-keycloak

resources:
  - ../../operator-manifests/red-hat-keycloak
  - Certificate_demo-tls.yaml
  - Keycloak_stp-devops-keycloak.yaml
