---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: PLACEHOLDER
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: PLACEHOLDER
  destinations:
    - namespace: PLACEHOLDER
      server: https://kubernetes.default.svc
      name: in-cluster
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: PLACEHOLDER
spec:
  destination:
    namespace: PLACEHOLDER
    server: https://kubernetes.default.svc
  project: PLACEHOLDER
  source:
    path: apps
    repoURL: https://github.com/ryan-highley/stp-devops-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
