apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: AppProject
      name: PLACEHOLDER
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: red-hat-keycloak
      spec:
        description: 'Red Hat build of Keycloak Project'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
    options:
      allowNameChange: true

transformers:
  - ../../base/transformers
