---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: PLACEHOLDER
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: PLACEHOLDER
  destinations: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: PLACEHOLDER
spec:
  destination: {}
  project: PLACEHOLDER
  source:
    path: manifests/app
    repoURL: https://github.com/ryan-highley/stp-devops-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
---
