apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../_manifest-template
  - ClusterRoleBinding_argocd-application-controller.yaml

patches:
  - target:
      kind: AppProject
      name: PLACEHOLDER
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: openshift-gitops
      spec:
        description: 'OpenShift GitOps Project'
        destinations:
          - name: in-cluster
            server: https://kubernetes.default.svc
            namespace: openshift-gitops

    options:
      allowNameChange: true

transformers:
  - ../_manifest-template/transformers
