apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-profile-operators
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: 'Project supporting all Operators required for a cluster profile'
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
