---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
data:
  name: c3RwLWRldm9wcy1jb25maWc=
  project: Kg==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL3J5YW4taGlnaGxleS9zdHAtZGV2b3BzLWNvbmZpZy5naXQ=
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: stp-devops-config-repo
  namespace: openshift-gitops
type: Opaque
---
